# Generated by Django 5.0.1 on 2024-03-12 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_delete_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.CharField(default='', max_length=620),
        ),
        migrations.AddField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userPosts',
            field=models.ManyToManyField(blank=True, related_name='userPosts', to='network.post'),
        ),
    ]
