# Generated by Django 5.0.1 on 2024-03-13 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_like_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='userFollowers', to=settings.AUTH_USER_MODEL)),
                ('followingOthers', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='followingOthers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
