# Generated by Django 5.0.1 on 2024-03-15 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(default='', max_length=100)),
                ('profileImg', models.URLField(default='', max_length=600)),
                ('bannerImg', models.URLField(default='', max_length=600)),
                ('dob', models.DateField(blank=True)),
                ('about', models.CharField(default='', max_length=600)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='userPosts',
        ),
    ]
