# Generated by Django 5.0.1 on 2024-03-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_userinfo_about_remove_userinfo_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bannerImg',
            field=models.URLField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='user',
            name='profileImg',
            field=models.URLField(default='', max_length=600),
        ),
    ]
