# Generated by Django 5.0.1 on 2024-03-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_user_bannerimg_user_profileimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='bannerImg',
            new_name='coverImg',
        ),
    ]
