# Generated by Django 5.0.1 on 2024-03-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_rename_bannerimg_userinfo_coverimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bannerImg',
            new_name='coverImg',
        ),
    ]
