# Generated by Django 5.0.1 on 2024-03-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_rename_bannerimg_user_coverimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coverImg',
            field=models.URLField(default='', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profileImg',
            field=models.URLField(default='', max_length=600, null=True),
        ),
    ]
