# Generated by Django 5.0.1 on 2024-03-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_user_coverimg_alter_user_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userPosts',
            field=models.ManyToManyField(blank=True, related_name='userPosts', to='network.post'),
        ),
    ]
