# Generated by Django 5.0.1 on 2024-03-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_userinfo_userposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='userPosts',
        ),
        migrations.AddField(
            model_name='user',
            name='userPosts',
            field=models.ManyToManyField(blank=True, related_name='userPosts', to='network.post'),
        ),
    ]
