# Generated by Django 5.0.1 on 2024-04-03 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_remove_userinfo_userposts_user_userposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userLikes',
            field=models.ManyToManyField(blank=True, related_name='userLikes', to='network.like'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='coverImg',
            field=models.URLField(blank=True, default='', max_length=1050, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profileImg',
            field=models.URLField(blank=True, default='', max_length=1050, null=True),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
